def generate_report(sector: str, news_items: list) -> str:
    """
    Generate a markdown report summarizing the news for the given sector.
    """
    report = f"# Market Analysis Report: {sector.capitalize()}\n\n"

    report += "## 📰 Latest News\n"
    for idx, (title, url) in enumerate(news_items, 1):
        report += f"{idx}. [{title}]({url})\n"

    report += "\n## ✅ Trade Opportunities\n"
    report += "- Expanding demand across domestic and international markets\n"
    report += "- Potential for government policy support\n"
    report += "- Increasing innovation and technology adoption\n"

    report += "\n## ⚠️ Risks & Challenges\n"
    report += "- Regulatory uncertainties\n"
    report += "- Dependence on global supply chains\n"
    report += "- Competition from established players\n"

    report += "\n## 🔮 Outlook\n"
    report += f"The outlook for the **{sector}** sector in India is cautiously optimistic " \
              f"with significant long-term growth opportunities.\n"

    report += "\n---\n*Generated by Trade Opportunities API MVP*"

    return report