import google.generativeai as genai
from core.config import settings

# Configure Gemini client
genai.configure(api_key=settings.GEMINI_API_KEY)

def generate_report(sector: str, news_items: list) -> str:
    """
    Calls the Gemini API to analyze sector news and return a markdown report.
    """
    # ✅ Prepare input context
    headlines_text = "\n".join([f"- {title} ({url})" for title, url in news_items])
    
    prompt = f"""
You are a trade research assistant. Analyze the following recent news headlines for the **{sector} sector in India**.

Headlines:
{headlines_text}

Generate a structured **Markdown Report** with the following sections:

# Market Analysis Report: {sector.capitalize()}

## 📊 Market Overview
(2-3 sentences summary of market trends from headlines)

## ✅ Trade Opportunities
- At least 3 bullet points with opportunities

## ⚠️ Risks & Challenges
- At least 3 bullet points with risks

## 🔮 Outlook
(2-3 sentences with future expectations about the sector)

---
*Generated by Trade Opportunities API*
"""

    # ✅ Call Gemini
    model = genai.GenerativeModel("gemini-2.5-flash-lite")
    response = model.generate_content(prompt)

    return response.text  # already Markdown formatted